# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
# 生成Windows下的可执行文件

name: Python windows pdf application

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      working-directory: Office/PDF_Tools
      shell: powershell
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
        if (Test-Path "requirements.txt") { pip install -r requirements.txt }

    - name: build
      working-directory: Office/PDF_Tools
      run: |
        pyinstaller -F image2Pdf.py
        pyinstaller -F mergePdf.py
        pyinstaller -F rotatePdf.py
        pyinstaller -F selectedPDFPages.py
        pyinstaller -F splitPDFPages.py
    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
          name: pdf-tools-exe
          path: Office/PDF_Tools/dist/*.exe
